film = input("Наименование фильма: ")
cinema = input("Название кинотеатра: ")
time = input("Время сеанса: ")
message = "Билет на фильм [%s] в кинотетре [%s] на [%s часов] забронирован." %(film, cinema, time)
print(message)